### PR TITLE
jScrollPane reinitialization should adapt to changed container size

### PR DESCRIPTION
**Pull request by ept**
I often want the height of my jScrollPane container to be able to change size, depending on the context of the surrounding page. However, once jScrollPane has been initialized, it is 'locked' to its initial size, and won't increase its size, even if more space is later available.

I have changed the reinitialization flow to reexamine the available space, and resize if necessary. I've also included a little demo page illustrating the change.

Cheers,
Martin

### CODE REVIEW

**Comment by illuusio** [comment]
Hello @ept  I'm trying to get jScrollPane development going again and try to clean up old PRs and bugs. Is this PR still relevant?

**Comment by ept** [comment]
@illuusio I no longer use jScrollPane and I have no idea what has changed in the 5 years since I last looked at this. This PR contains a HTML file with a test case — I suggest trying it to see if the bug is still present.

**Comment by illuusio** [comment]
Thank you for input. I'll try it.

**Comment by illuusio** [comment]
Ok I re-arranged this to new PR and merge it to master. Thanks for work.

**Pull request closed without merging**
