### PR TITLE
Register to globally available version of jQuery

### PR DESCRIPTION
**Pull request by abhishekdev**
I am not entirely sure about the maintainers preferences here, but it seems importing the plugin in a ES6 environment has no effect.

### Issue:
The plugin does not register on window.jquery OR to the locally available jQuery in the module.

### Expectation
- The plugin should register itself to the global available jQuery  or the local ES6 import

### Sample code

Contents of **<root>main.js**

```js
import jQuery from './jquery-shim';
import 'jquery-ui-dist/jquery-ui';
import 'jquery-mousewheel';
import 'jscrollpane/script/jquery.jscrollpane';
```

Contents of **<root>/jquery-shim.js**

```js
import jQuery from 'jquery';
// expose jQuery on window, so that non ES6 legacy plugins (incl. jquery-ui) may work
window.jQuery = window.$ = jQuery;

export default jQuery;
```

The pull requests gives preference to the globally available jquery (if present) before using the private jquery dependency as a fallback

### CODE REVIEW

**Comment by illuusio** [comment]
Thank you for contribution! How does this work on ES5 which is current normal?

**Comment by abhishekdev** [comment]
I had not verified this before. However, it seems the plugin does not work in CommonJS code as well. It works on the ES5 browser environment as it registers on the globally available `jQuery` object.

CommonJS code:

```js
var jquery = require('jquery')
var jscrollpane = require("jscrollpane")

console.log(jquery.fn.jscrollpane, jscrollpane);
```
Run Testcase: https://runkit.com/embed/5vp5rhyarvj7

**Comment by illuusio** [comment]
Can you update to new release

**Comment by abhishekdev** [comment]
Sure! Updated to latest master.

Also here is an updated testcase: https://runkit.com/embed/6bn0ostlytwz

**Comment by illuusio** [comment]
One more thing as this is 'big' change I think we'll follow RC path so could you add this to rc1. Nobody can say I break their favorite tool.

**Comment by abhishekdev** [comment]
So would you update the version numbers (to include RC suffix) in the changelog as well?

Just wanted to make sure my understanding is correct and there is nothing more on my plate.

Thanks again for looking into this.

**Comment by illuusio** [comment]
Actually It would be easiest to remove Changelog or make it 2.2.1-rc.1 if you like to keep it. I'll make release after this as I can this make somebody unhappy.

**Comment by abhishekdev** [comment]
Removed changelog.

**Comment by illuusio** [comment]
Merged thanks!

**Pull request merged**
