### PR TITLE
Simplify UMD pattern

### PR DESCRIPTION
**Pull request by edull24**
Fixes browserify when loading jQuery outside of bundle. In the old
pattern, jQuery is undefined when it is loaded externally, such as from
a CDN. The UMD pattern now follows:
https://github.com/umdjs/umd/blob/master/jqueryPluginCommonjs.js

### CODE REVIEW

**Comment by vitch** [comment]
Awesome - thanks! 

Can you generate the minified version as well please (via the `grunt` task described in the README)?

**Comment by edull24** [comment]
The minified version should be part of the pull request already. Is it not showing up for you? You may have missed it since it is not expanded by default when viewing the changed files.

**Comment by vitch** [comment]
My bad! Thanks again :smile:

**Comment by edull24** [comment]
No problem, thanks for all the work on the plugin!

**Pull request merged**
