### PR TITLE
Fix README and add Ruby gem

### PR DESCRIPTION
**Pull request by bodrovis**
jScrollPane is available as Ruby gem (gem is a fancy word for library in Ruby) :) https://github.com/bodrovis/jscrollpane-rails

What's interesting, the gem was already mentioned [on the website](http://jscrollpane.kelvinluck.com/) by  the previous maintainer but for some reason in the "Simple examples" section. Perhaps, it should be moved to "Download".

### CODE REVIEW

**Comment by illuusio** [comment]
Thank you for contribution. webpage is more or less unmaintained or? I don't if I should setup more recent version of webpage. As this could be nice addition I suppose after adding Ruby version it should also add link to other versions.

**Comment by vitch** [comment]
The webpage is simply the contents of [the `examples` directory of this repo](https://github.com/vitch/jScrollPane/tree/master/examples). 

Unfortunately I need to manually deploy it and I hadn't done that it a while...

I just deployed the latest and I will make sure to do so when new versions of the package are published...

**Comment by bodrovis** [comment]
I think you may utulize [GitHub pages](https://pages.github.com/) which requires no deploy at all - you just push commit and changes are reflected on the site.

**Comment by illuusio** [comment]
Sorry @bodrovis  and @vitch I was in hurry and just though to myself about that and push comment button before thinking.. :dancer: . Can you tune your PR to only make one change. Add that link and nothing else because now there is some changes that don't belong to this issue. I'll sort out levels or make another PR for them.

**Comment by bodrovis** [comment]
Yeah, I'll reopen a new one.

**Pull request closed without merging**
