### PR TITLE
Fixes issue where pane is left scrolled too far after reinitialising in ...

### PR DESCRIPTION
**Pull request by gavinaiken**
Fixes issue where pane is left scrolled too far after reinitialising in cases where the content is barely bigger than the scroll pane (contentHeight - paneHeight == 0)

### CODE REVIEW

**Comment by localshred** [comment]
Any chance this can be merged? We're currently patching this library with these fixes and would love to help test and move this forward.

**Comment by illuusio** [comment]
After all these years is this still relevant?

**Comment by gavinaiken** [comment]
I can't say for sure, I created this PR while working for a company which was using jScrollPane at the time, but I left that company nearly 3 years ago. When I left they were still using jScrollPane with this change, so it was certainly relevant then. Not sure any more though!

**Comment by illuusio** [comment]
Kind of trivial change so have to test and merge if I see it necesery

**Comment by illuusio** [comment]
Please test Resize sensor and update this PR (reopen) if it doesn't solve your problem.

**Pull request closed without merging**
