### PR TITLE
added suggested fix of @aphillips8 in #143 to update height on reinitial...

### PR DESCRIPTION
**Pull request by tylkomat**
...ize

### CODE REVIEW

**Comment by illuusio** [comment]
Is this still relevant and can you tell how to test this.

**Comment by tylkomat** [comment]
Sorry after two years, I can't really remember. But we are using it in production for some time.

**Comment by illuusio** [comment]
With this patch included?

**Comment by tylkomat** [comment]
Yes.

**Comment by illuusio** [comment]
Can you tell which kind of operation requires this patch if you can give any clues because this seems to be good formed patch? Resizing window or resizing area of pane?

**Comment by tylkomat** [comment]
[This](https://github.com/vitch/jScrollPane/issues/143) is the original issue. I remember now. In our case the problem was: There is a list of items larger than the screen. Then you apply a filter to the list and the items become less and fit into a screen, but the scrollpane still has scrollbars and keeps the original height of when it was first initialized.

**Comment by illuusio** [comment]
Ok thanks I try to take a look at this when I have time and integrate if it feels correct

**Comment by illuusio** [comment]
Can you test PR vitch/jScrollPane#361 does that fix this issue?

**Comment by illuusio** [comment]
This should be fixed with 2.2.0 if not please feel free to re-open.

**Pull request closed without merging**
