### PR TITLE
jScrollPane jQuery update to version 3.x

### PR DESCRIPTION
**Pull request by illuusio**
This is minimal update to support jQuery 3.x which replace  jQuery.fn.bind(),  jQuery.fn.unbind() and jQuery.fn.hover(). Probably breaks compability to 1.x and maybe 2.x. Updates also HTML examples.

### CODE REVIEW

**Comment by vitch** [comment]
Thanks for this PR.

Unfortunately I don't really maintain this plugin any more. Would you be interested in being granted commit permissions to the repository?

**Comment by illuusio** [comment]
I don't see it won't hurt anyone in this situation. I could wander through other PR's and try to close them or get them in if they are still relevant. In some point of time it could be nice to have organization but I don't know if this is big enough?

**Comment by vitch** [comment]
I have tried to add you as a collaborator - let me know if it works for you...

**Comment by illuusio** [comment]
Thanks.. Is it ok to make new Release after this have been merged?

**Comment by vitch** [comment]
Sure. Just follow SemVer rules for the release numbering...

**Comment by vitch** [comment]
Thanks!

**Pull request merged**
